// Adapted from spiceai/powerbi-connector (MIT License, (c) 2025 Spice AI, Inc.)
let
    TypeInfo = Extension.LoadExpression("TypeInfo.pqm"),
    FlightSqlAdbcConfig = [
        Name = "FlightSqlAdbcGizmoSQL",
        Folder = "FlightSQL",
        File = "libadbc_driver_flightsql.dll",
        DriverType = "Unmanaged",
        EntryPoint = "FlightSqlDriverInit",
        IdentifierQuoteChar = """",
        CatalogNameSeparator = ".",
        TableTypes = "BASE TABLE",
        SupportsCatalog = true,
        SupportsSchema = true,
        SupportedConnectionOptions = [
            adbc.connection.catalog = true,
            adbc.connection.db_schema = false
        ],
        TypeInfo = Table.SelectColumns(
            TypeInfo,
            {"Name", "SqlType", "Unsigned", "ColumnSize", "NumberPrecisionRadix", "LiteralPrefix", "LiteralSuffix"}
        )
    ],
    Extension.LoadExpression = (name as text) =>
        let
            binary = Extension.Contents(name), asText = Text.FromBinary(binary)
        in
            Expression.Evaluate(asText, #shared)
in
    FlightSqlAdbcConfig
